config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/discord', to: 'pages#discord'
  get '/signup', to: 'users#new'
  
  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete
  
  match 'follow', to: 'follows#follow', via: :post
  match 'unfollow', to: 'follows#unfollow', via: :delete
  
  match 'notifications/send', to: 'notifications#create', via: :post
  
  resources :notifications, only: [:show] do
    member do
      match :read, to: 'notifications#read', via: :post
      match :delete, to: 'notifications#delete', via: :delete
    end
  end
  
  resources :users do
    member do
      get :notifications
      post :read_all_notifications
      post :delete_all_notifications
    end
  end
  
  resources :users, except: [:new]
  resources :posts
  resources :comments, except: [:new, :index, :show] do
    member do
      put :undelete
    end
  end
  
  post 'comments/new', to: 'comments#create'
  
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #belongs_to :post
  belongs_to :commentable, polymorphic: true
  #belongs_to :parent_comment
  belongs_to :user
  
  has_many :comments, as: :commentable
  
  def head_parent
    parent = self
    while parent.commentable_type == "Comment" do
      parent = parent.commentable
    end
    puts '----------------------------------------------------------', parent, parent.id, parent.commentable_type
    return parent.commentable
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :update, :destroy, :undelete]
	before_action :require_user
	before_action :require_same_user, only: [:edit, :update, :destroy]
	
    def new
	    @comment = Comment.new
    end
	
	def edit
	end
	
	def create
		@comment = Comment.new(comment_params)
		@comment.user = current_user
		if not params[:comment][:parent_comment] then
			@comment.commentable = Post.find(params[:comment][:post_id])
		else
			@comment.commentable = Comment.find(params[:comment][:parent_comment])
		end
		
		puts '----------------------------------------------------', @comment.commentable.id
		
		if @comment.save then
			# send notifications to the posts owner
			if @comment.commentable_type == "Post" then
				@comment.commentable.user.create_notification("#{current_user.username} commented on your post, \"#{@comment.commentable.name}\"", @comment.body.truncate(250)) 
				flash[:success] = "Comment was successfully created"
				redirect_to post_path(@comment.commentable)
			else
				flash[:success] = "Comment was successfully created"
				redirect_to post_path(@comment.head_parent)
			end
		else
			render 'new'
		end
	end
	
	def destroy
		commentable = @comment.commentable
		@comment.deleted = true
		if @comment.save then
			flash[:success] = "Comment was successfully deleted"
			if @comment.commentable_type == "Post" then
				redirect_to post_path(commentable)
			else
				redirect_to post_path(@comment.head_parent)
			end
		else
			flash[:danger] = "Error deleting comment"
			redirect_to post_path(commentable)
		end
	end
	
	def undelete
		commentable = @comment.commentable
		@comment.deleted = false
		if @comment.save then
			flash[:success] = "Comment was successfully undeleted"
			if @comment.commentable_type == "Post" then
				redirect_to post_path(commentable)
			else
				redirect_to post_path(@comment.head_parent)
			end
		else
			flash[:danger] = "Error undeleted comment"
			redirect_to post_path(commentable)
		end
	end
	
	def update
		if @comment.update(comment_params) then
			flash[:success] = "Comment was successfully updated"
			if @comment.commentable_type == "Post" then
				redirect_to post_path(commentable)
			else
				redirect_to post_path(@comment.head_parent)
			end
		else
			render 'edit'
		end
	end
	
	private
		def set_comment
			@comment = Comment.find(params[:id])
		end
		
		def comment_params
			puts '----------------------------------------', params
			params.require(:comment).permit(:body)
		end
		
		def require_same_user
			if current_user != @comment.user and not current_user.admin? then
				flash[:danger] = "You can only edit or delete your own comments"
				redirect_to root_path
			end
		end
end

app/views/comments/_child_comments.html.erb
<% if Comment.where(commentable: comment).length > 0 then %>
    <div class="collapse-section" id="<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_show_more" %>" style="display: none; visibility: hidden;" data-collapsed="true">
        <span style="cursor: pointer;"
            onclick="hideElementSlideUp('<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_content" %>');
            toggleElementDisplay('<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_show_more" %>');
            toggleElementDisplay('<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_show_less" %>')">
            <small>Show comments</small><i class="material-icons icon-low" style="font-size: 18px;">expand_more</i>
        </span>
    </div>
    <div class="collapse-section" id="<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_show_less" %>">
        <span style="cursor: pointer;"
            onclick="hideElementSlideUp('<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_content" %>');
            toggleElementDisplay('<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_show_less" %>');
            toggleElementDisplay('<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_show_more" %>')">
            <small>Hide comments</small><i class="material-icons icon-low" style="font-size: 18px;">expand_less</i>
        </span>
    </div>
     <div class="collapse-section" id="<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}_content" %>">
        <div class="group" id="<%= "comment_#{comment.id}_sub_comments_div_layer_#{layer}" %>">
            <% sub_comments = Comment.where(commentable: comment) %>
            <% sub_comments.each.with_index do |comment, index| %>
                <% row = row + (layer == 0 ? 1 : 0) %>
                <a id="<%= "comment_#{row}:#{layer}:#{index}" %>"></a>
                <% if comment.deleted then %>
                    <div class="comment-deleted">This comment has been deleted</div>
                    <% if comment.user == current_user then %><br><%= link_to "Undelete", undelete_comment_path(comment), method: :put, class: "btn btn-xs btn-primary" %><% end %>
                    <br><br>
                    <%= render "comments/child_comments", comment: comment, row: row, layer: layer + 1 %>
                <% else %>
                    <div class="comment"><%= simple_format(comment.body != "" ? comment.body : raw("<br>"), {}, wrapper_tag: 'span') %></div><br>
                    <% if comment.created_at != comment.updated_at then %><small><sup>(edited)</sup></small><br><% end %>
                    <small><sup><%= link_to @post.user.username, user_path(@post.user), class: "link" %></sup></small><br>
                    <% if comment.user == current_user then %><%= link_to "Edit", edit_comment_path(comment), class: "btn btn-sm btn-primary" %><% end %>
                    <% if comment.user == current_user then %><%= link_to "Delete", comment_path(comment), method: :delete, class: "btn btn-sm btn-danger" %><% end %>
                    <%= link_to "Reply", "javascript:void(0)", class: "btn btn-sm btn-success", :onclick => "toggleElementDisplay('reply_to_comment_#{row}:#{layer}:#{index}_form');" %>
                    <br>
                    <br>
                    <div class="group" style="visibility: hidden;display: none;" id="<%= "reply_to_comment_#{row}:#{layer}:#{index}_form" %>">
                        <%= form_tag comments_new_path, method: :post do %>
                            <%= hidden_field_tag "comment[post_id]", @post.id %>
                            <%= hidden_field_tag "comment[parent_comment]", comment.id %>
                            <textarea class="textarea" name="comment[body]"></textarea>
                            <br>
                            <%= submit_tag "Submit", class: "btn btn-sm btn-primary" %>
                            <%= link_to "Cancle", "javascript:void(0)", class: "btn btn-sm", :onclick => "toggleElementDisplay('reply_to_comment_#{row}:#{layer}:#{index}_form');;" %>
                        <% end %>
                    </div>
                    <%= render "comments/child_comments", comment: comment, row: row, layer: layer + 1 %>
                <% end %>
                <% if not index == sub_comments.length - 1 then %>
                    <hr>
                <% end %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
    <h2>The following errors prevented the comment from getting created</h2>
    
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= @comment.errors.full_messages.length %> errors prohibited this comment from being saved</p>
        <% @comment.errors.full_messages.each do |msg| %>
            <p>&emsp;
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= msg %>
            </p>
        <% end %>
    </div>
<% end %>

<%= form_for(@comment, :html => {role: "form"}) do |f| %>
        <%= f.label :body %><br>
        <%= f.text_area :body, rows: 4, class: "textarea form-control", placeholder: "Comment body", autofocus: true %>
        <hr>
        <%= f.submit class: "btn btn-primary"%>
        <%= link_to "Back to posts", post_path(@comment.commentable), class: 'btn btn-sm float-right' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit existing post</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<br>
<%= link_to "Create new post", new_post_path, class: "btn btn-xs btn-primary" %>
<br>
<br>

<script>
$(document).ready(function() {
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#table tr .search-field").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<input class="input size-narrow" id="search" type="text" placeholder="Search...">
  
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Created by</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody id="table">
    <% @posts.each do |post| %>
        <tr>
            <td><%= post.name %></td>
            <td><%= truncate(post.body, length: 50) %></td>
            <td><%= if post.user then link_to(post.user.username, user_path(post.user), :class => "link") else "Unknown" end %>
            <% if logged_in? and (current_user == post.user or current_user.admin?) then %>
                <td>
                <%= div_for post do %>
                    <%= render partial: "likes/button", locals: { post: post } %>
                <% end %>
                </td>
                <td><%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %></td>
                <td><%= link_to "Delete", post_path(post), method: :delete, 
                    data: {confirm: "Are you sure you want to delete this post?"}, 
                    class: "btn btn-xs btn-danger" %></td>
            <% else %>
                <td><button class="btn btn-xs btn-primary" disabled>Edit</button></td>
                <td><button class="btn btn-xs btn-danger" disabled>Delete</button></td>
            <% end %>
            <td><%= link_to "View", post_path(post), class: "btn btn-xs btn-success" %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/comments/new.html.erb
<h1>Create an post</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<% if @post.errors.any? %>
<h2>The following errors prevented the post from getting created</h2>

    <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
            <p>
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            <%= msg %>
            </p>
        </div>
    <% end %>
<% end %>

<h1 align="center"><%= @post.name %><br>by: <%= link_to @post.user.username, user_path(@post.user), class: "link" %></h1>

<div class="column-row">
    <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-1-if-med column-2-if-lg column-2-if-xl">
        <br>
    </div>
    
    <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-10-if-med column-8-if-lg column-8-if-xl">
        <div class="well">
            <h4 class="center"><string><%= @post.name %></string></h4>
            <hr>
            <% text = @post.body %>
            <% text = text.gsub(/:([^"\s]*):/) do |string| %>
                <% "<i class=\"icon-low material-icons\" style=\"font-size: 38px;\">#{string[1..-2]}</i>" %>
            <% end %>
            <% text = text.gsub(/:\)/) do |string| %>
                <% "<i class=\"icon-low material-icons\" style=\"font-size: 38px;\">sentiment_very_satisfied</i>" %>
            <% end %>
            <% text = text.gsub(/:\(/) do |string| %>
                <% "<i class=\"icon-low material-icons\" style=\"font-size: 38px;\">sentiment_very_dissatisfied</i>" %>
            <% end %>
            <% text = text.gsub(/:\|/) do |string| %>
                <% "<i class=\"icon-low material-icons\" style=\"font-size: 38px;\">sentiment_neutral</i>" %>
            <% end %>
            <% text = text.gsub(/D:/) do |string| %>
                <% "<i class=\"icon-low material-icons\" style=\"font-size: 38px;\">mood_bad</i>" %>
            <% end %>
            <%= simple_format(text) %>
            <hr>
            tags:
            <% @post.tags.each do |tag| %>
                <span class="span-group btn-primary"><%= tag %></span>
            <% end %>
            <br>
            <%= @post.likes.length %> <%= @post.likes.length > 1 ? "users have" : "user has" %> liked this post
            <br>
            <div class="post-actions">
               <% if logged_in? and (current_user == @post.user or current_user.admin?) %>
                    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete", post_path(@post), method: :delete, 
                    data: {confirm: "Are you sure you want to delete this post?"}, 
                    class: "btn btn-xs btn-danger" %>
                <% else %>
                    <td><button class="btn btn-xs btn-primary" disabled>Edit</button></td>
                    <td><button class="btn btn-xs btn-danger" disabled>Delete</button></td>
                <% end %>
                <%= link_to "All posts", posts_path, class: "btn btn-xs btn-success" %>
                <%= div_for @post, :style => "display: inline-block;" do %>
                    <%= render partial: "likes/button", locals: { post: @post } %>
                <% end %>
            </div>
        </div>
    </div>
    
    <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-1-if-med column-2-if-lg column-2-if-xl">
        <br>
    </div>
    
    <div class="column column-12">
        <%= link_to "Back to posts listing", posts_path, :class => "btn btn-sm" %>
    </div>
</div>