config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/discord', to: 'pages#discord'
  get '/signup', to: 'users#new'
  
  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete
  
  match 'follow', to: 'follows#follow', via: :post
  match 'unfollow', to: 'follows#unfollow', via: :delete
  
  match 'notifications/send', to: 'notifications#create', via: :post
  
  resources :notifications, only: [:show] do
    member do
      match :read, to: 'notifications#read', via: :post
      match :delete, to: 'notifications#delete', via: :delete
    end
  end
  
  resources :users do
    member do
      get :notifications
      post :read_all_notifications
      post :delete_all_notifications
    end
  end
  
  resources :users, except: [:new]
  resources :posts
  resources :comments, except: [:new, :index, :show] do
    member do
      put :undelete
    end
  end
  
  post 'comments/new', to: 'comments#create'
  
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_posts, :through => :likes, :source => :post
    
    has_many :followers, :class_name => 'Follow', :foreign_key => 'user_id'
    has_many :following, :class_name => 'Follow', :foreign_key => 'follower_id'
    
    has_many :comments, as: :commentable
    
    before_save {self.email = email.downcase}
    validates :username, presence: true, uniqueness: {case_sensitive: false},
                length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false},
                length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
    has_secure_password
    
    # creates a new like row with post_id and user_id
    def like!(post)
        self.likes.create!(post_id: post.id)
    end
    
    # destroys a like with matching post_id and user_id
    def unlike!(post)
        like = self.likes.find_by_post_id(post.id)
        like.destroy!
    end
    
    # returns true if a post is liked by user
    def like?(post)
        self.likes.find_by_post_id(post.id)
    end
    
    # creates a new follow row with followed_user_id and user_id
    def follow!(follower)
        #puts '-----------------------------------------------------------------'
        #puts follower.username
        #puts self.username
        #puts '-----------------------------------------------------------------'
        self.followers.create!(follower_id: follower.id)
    end
    
    # destroys a follow with matching followed_user_id and user_id
    def unfollow!(follower)
        follow = self.followers.find_by_post_id(follower.id)
        follow.destroy!
    end
    
    # returns true if a follower is followed by user
    def follow?(follower)
        follower.following.any? {|e| e.user.id == self.id}
    end
    
    # creates a notification with a user_id of this user (self)
    def create_notification(title, body)
        @notification = Notification.new
		@notification.user = self
		@notification.title = title
		@notification.body = body
		
		# puts '--------------------------------', @notification.user_id, @notification.body
		
		@notification.save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy, :notifications, :read_all_notifications, :delete_all_notifications]
	before_action :require_same_user, only: [:edit, :update, :destroy, :notifications, :read_all_notifications, :delete_all_notifications]
	before_action :require_admin, only: [:destroy]
	
    def index
		@users = User.all
    end
    
    def notifications
        @notifications = Notification.where(:user => @user)
    end
    
    def new
       @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save then
            session[:user_id] = @user.id
            flash[:success] = "Welcome, #{@user.username}!"
            redirect_to user_path(@user)
        else
            render 'new' 
        end
    end
    
    def edit
    end
    
    def update
        if @user.update(user_params) then
            flash[:success] = "Yout account was successfully updated"
            redirect_to user_path(@user)
        else
            render 'edit' 
        end
    end
    
    def show
    end
    
    def destroy
        @user.destroy
        flash[:danger] = "User and all theirs users have been destroyed"
        redirect_to users_path
    end
    
    def read_all_notifications
        @notifications = Notification.where(:user => @user)
        @notifications.each do |notification|
            notification.read = true
            notification.save
        end
        redirect_back fallback_location: notifications_user_path(@user)
    end
    
    def delete_all_notifications
        @notifications = Notification.where(:user => @user)
        @notifications.each do |notification|
            notification.destroy
        end
        redirect_back fallback_location: notifications_user_path(@user)
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :description)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
        if not logged_in? then
            flash[:danger] = "You can only edit your own account"
			redirect_to root_path
        elsif current_user != @user and current_user.admin < @user.admin then
            flash[:danger] = "You can only edit your own account"
			redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and not current_user.admin > 0 then
            flash[:danger] = "Only admins can preform that acction"
            redirect_to root_path
        end
    end
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <h2>The following errors prevented the user from getting created</h2>
    
    <div class="alert alert-danger" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <p><%= @user.errors.full_messages.length %> errors prohibited this user from being saved</p>
        <% @user.errors.full_messages.each do |msg| %>
            <p>&emsp;
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= msg %>
            </p>
        <% end %>
    </div>
<% end %>

<%= form_for(@user, :html => {role: "form"}) do |f| %>
    <div>
        <%= f.label :username %><br>
        <%= f.text_field :username, class: "input", placeholder: "Enter username", autofocus: true %>   
    </div>
    <div>
        <%= f.label :email %><br>
        <%= f.email_field :email, class: "input", placeholder: "Enter email", autofocus: true %>
    </div>
    <div>
        <%= f.label :password %><br>
        <%= f.password_field :password, class: "input", placeholder: "Enter password", autofocus: true %>   
    </div>
    <div>
        <%= f.label :description %> <small>(optional)</small><br>
        <%= f.text_area :description, class: "textarea", placeholder: "Enter description", autofocus: true, rows: 4 %>   
    </div>
    <hr>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary") %>
    <%= link_to 'Cancel', @user.new_record? ? root_path : user_path(@user), class: 'btn' %>
    <%= link_to "Back to users listing", users_path, class: 'btn btn-sm float-right' %>
    <% if @user.new_record? then %>
        <hr>
        Already have an account?
        &nbsp;&nbsp;
        <%= link_to "Login", login_path, class: 'btn btn-primary' %>
    <% end %>
<% end %>  

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form', type: 'edit' %>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= link_to "Signup", signup_path, class: "btn btn-xs btn-primary" %>
<br>
<br>

<script>
$(document).ready(function() {
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#table tr .search-field").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<input class="input size-narrow" id="search" type="text" placeholder="Search...">
  
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody id="table">
    <% @users.each do |user| %>
        <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <% if logged_in? and (current_user == user or current_user.admin?) then %>
                <td><%= link_to "Edit", edit_user_path(user), class: "btn btn-xs btn-primary" %></td>
                <td><%= link_to "Delete", user_path(user), method: :delete, 
                    data: {confirm: "Are you sure you want to delete this user?"}, 
                    class: "btn btn-xs btn-danger" %></td>
            <% else %>
                <td><button class="btn btn-xs btn-primary" disabled>Edit</button></td>
                <td><button class="btn btn-xs btn-danger" disabled>Delete</button></td>
            <% end %>
            <td><%= link_to "View", user_path(user), class: "btn btn-xs btn-success" %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>

<%= render 'form', type: 'new' %>

app/views/users/notifications.html.erb
<h1 align="center">Notifications:</h1>
<!--
<% 'user home users sign-in-alt sign-out-alt bars bell file-alt'.split.each do |icon| %>
    <i class="fas fa-<%= icon %>" style="color: #666;text-shadow: 1px 1px 1px #ccc;font-size: 38px;"></i>
<% end %>
-->
<div class="column-row">
    <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-1-if-med column-2-if-lg column-2-if-xl">
        <br>
    </div>
    
    <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-10-if-med column-8-if-lg column-8-if-xl">
        <% if logged_in? and (current_user == @user or current_user.admin?) %>
            <% if logged_in? and current_user.admin > 0 then %>
                <%= div_for @user, :style => "display: inline-block;" do %>
                    <%= button_to notifications_send_path(user_id: @user.id, notification_title: "title_created", notification_body: "body_created"), remote: true, :class => "btn btn-primary btn-sm" do %>
                        New
                    <% end %>
                <% end %>
            <% end %>
            <%= div_for @user, :style => "display: inline-block;" do %>
                <%= button_to read_all_notifications_user_path(user_id: @user.id, notification_title: "title_created", notification_body: "body_created"), remote: true, :class => "btn btn-danger btn-sm", 'data-disable-with' => "Loading..." do %>
                    Mark all as read
                <% end %>
            <% end %>
            <%= div_for @user, :style => "display: inline-block;" do %>
                <%= button_to delete_all_notifications_user_path(user_id: @user.id, notification_title: "title_created", notification_body: "body_created"), remote: true, :class => "btn btn-danger btn-sm", 'data-disable-with' => "Loading..." do %>
                    Delete all
                <% end %>
            <% end %>
        <% end %>
        <hr>
        <% @notifications.each do |notification| %>
            <strong><%= notification.title %>:</strong>
            <div class="<%= notification.read ? "well" : "group" %> overflow-hidden toolbar-container">
                <%= notification.body.truncate(100) %>
                <br><br>
                <div class="toolbar">
                    <%= link_to "Read", notification_path(notification), class: "btn btn-sm btn-primary" %>
                    <% if logged_in? and (current_user == @user or current_user.admin?) %>
                        <%= div_for @user, :style => "display: inline-block;" do %>
                            <%= button_to "Mark as read", read_notification_path(notification), remote: true, :class => "btn btn-sm btn-danger" %>
                        <% end %>
                        <%= div_for @user, :style => "display: inline-block;" do %>
                            <%= button_to "Delete", delete_notification_path(notification), remote: true, method: :delete, :class => "btn btn-sm btn-danger" %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
    
    <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-1-if-med column-2-if-lg column-2-if-xl">
        <br>
    </div>
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page </h1>

<div class="column-row">
    <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-1-if-med column-2-if-lg column-2-if-xl">
        <br>
    </div>
    <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-10-if-med column-8-if-lg column-8-if-xl column-row">
        <div class="group text-center column-row">
            <span><%= gravatar_for @user, size: 150, animated: true %></span>
            <hr>
            <% if current_user == @user %>
                <div class="text-left">
                    <%= link_to edit_user_path(@user), class: "btn btn-primary" do %>
                        Settings <span class="material-icons icon">settings</span>
                    <% end %>
                </div>
            <% else %>
                <div class="text-left">
                    <%= div_for current_user, :style => "display: inline-block;" do %>
                        <%= render partial: "follows/button", locals: { followed_user: @user } %>
                    <% end %>
                    <% @user.following.each do |follower| %>
                        <%= follower.user.username %>
                    <% end %>
                </div>
            <% end %>
            <br>
            <div class="text-left">
                <%= "#{@user.following.length} Follower#{'s' if @user.following.length != 1}" %>
            </div>
        </div>
        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
            <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-0-if-med column-1-if-lg column-2-if-xl">
                <br>
            </div>
            <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-10-if-lg column-8-if-xl">
                Description:
                <div class="group word-wrap height-px-200 overflow-scroll">
                    <%= @user.description %>
                </div>
            </div>
            <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-0-if-med column-1-if-lg column-2-if-xl">
                <br>
            </div>
        </div>
        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
        <h4>Your posts:</h4>
            <div class="group column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
                <div class="scrolling-wrapper">
                    <% Post.where(:user => @user).each do |post| %>
                        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl scrolling-wrapper-card">
                            <%= post.name %>:
                            <div class="group word-wrap toolbar-container">
                                <div class="height-px-200 overflow-scroll">
                                    <%= post.body.truncate(250) %>
                                </div>
                                <div class="toolbar">
                                    <% if logged_in? then %>
                                        <% if current_user == post.user or current_user.admin? %>
                                            <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
                                            <%= link_to "Delete", post_path(post), method: :delete, 
                                            data: {confirm: "Are you sure you want to delete this post?"}, 
                                            class: "btn btn-xs btn-danger" %>
                                        <% end %>
                                        <%= link_to "All posts", posts_path, class: "btn btn-xs btn-success" %>
                                        <%= link_to "View", posts_path, class: "btn btn-xs btn-success" %>
                                        <%= div_for post, :style => "display: inline-block;" do %>
                                            <%= render partial: "likes/button", locals: { post: post } %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
            <h4>Liked posts:</h4>
            <div class="group column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
                <div class="scrolling-wrapper">
                    <% @user.liked_posts.each do |post| %>
                        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                            <%= post.name %>:
                            <div class="group word-wrap toolbar-container">
                                <div class="height-px-200 overflow-scroll">
                                    <%= post.body.truncate(250) %>
                                </div>
                                <div class="toolbar">
                                    <% if logged_in? then %>
                                        <% if current_user == post.user or current_user.admin? %>
                                            <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
                                            <%= link_to "Delete", post_path(post), method: :delete, 
                                            data: {confirm: "Are you sure you want to delete this post?"}, 
                                            class: "btn btn-xs btn-danger" %>
                                        <% end %>
                                        <%= link_to "All posts", posts_path, class: "btn btn-xs btn-success" %>
                                        <%= link_to "View", posts_path, class: "btn btn-xs btn-success" %>
                                        <%= div_for post, :style => "display: inline-block;" do %>
                                            <%= render partial: "likes/button", locals: { post: post } %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
            <h4>Posts by your followers:</h4>
            <div class="group column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
                <div class="scrolling-wrapper">
                    <% @user.following.each do |follower| %>
                        <% follower.user.posts.each do |post| %>
                            <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                                <%= post.name %>:
                                <div class="group word-wrap toolbar-container">
                                    <div class="height-px-200 overflow-scroll">
                                        <%= post.body.truncate(250) %>
                                    </div>
                                    <div class="toolbar">
                                        <% if logged_in? then %>
                                            <% if current_user == post.user or current_user.admin? %>
                                                <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
                                                <%= link_to "Delete", post_path(post), method: :delete, 
                                                data: {confirm: "Are you sure you want to delete this post?"}, 
                                                class: "btn btn-xs btn-danger" %>
                                            <% end %>
                                            <%= link_to "All posts", posts_path, class: "btn btn-xs btn-success" %>
                                            <%= link_to "View", posts_path, class: "btn btn-xs btn-success" %>
                                            <%= div_for post, :style => "display: inline-block;" do %>
                                                <%= render partial: "likes/button", locals: { post: post } %>
                                            <% end %>
                                        <% end %>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
            <h4>Followers:</h4>
            <div class="group scrolling-wrapper">
                <% @user.following.each do |follower| %>
                    <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                        <%= follower.user.username %>:
                        <div class="group">
                            <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                                <%= link_to gravatar_for(follower.user), user_path(follower.user), class: "link" %>
                            </div>
                            <div class="height-px-85 overflow-scroll">
                                <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                                    <%= follower.user.description %>
                                </div>
                            </div>
                        </div>
                <% end %>
            </div>
        </div>
        <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-12-if-lg column-12-if-xl">
            <h4>Users you are following:</h4>
            <div class="group scrolling-wrapper">
                <% @user.followers.each do |follower| %>
                    <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                        <%= follower.follower.username %>:
                        <div class="group">
                            <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                                <%= link_to gravatar_for(follower.follower), user_path(follower.follower), class: "link" %>
                            </div>
                            <div class="height-px-85 word-wrap overflow-scroll">
                                <div class="column column-12-if-nano column-12-if-xs column-12-if-sm column-12-if-med column-6-if-lg column-4-if-xl">
                                    <%= follower.follower.description %>
                                </div>
                            </div>
                        </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="column column-0-if-nano column-0-if-xs column-0-if-sm column-1-if-med column-2-if-lg column-2-if-xl">
        <br>
    </div>
</div>