config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/discord', to: 'pages#discord'
  get '/signup', to: 'users#new'
  
  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete
  
  match 'follow', to: 'follows#follow', via: :post
  match 'unfollow', to: 'follows#unfollow', via: :delete
  
  match 'notifications/send', to: 'notifications#create', via: :post
  
  resources :notifications, only: [:show] do
    member do
      match :read, to: 'notifications#read', via: :post
      match :delete, to: 'notifications#delete', via: :delete
    end
  end
  
  resources :users do
    member do
      get :notifications
      post :read_all_notifications
      post :delete_all_notifications
    end
  end
  
  resources :users, except: [:new]
  resources :posts
  resources :comments, except: [:new, :index, :show] do
    member do
      put :undelete
    end
  end
  
  post 'comments/new', to: 'comments#create'
  
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/follow.rb
class Follow < ActiveRecord::Base
    belongs_to :user
    belongs_to :follower, :class_name => 'User'
    validates :user_id, uniqueness: { scope: :follower_id }
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    # respond_to :js
    
    def follow
        @user = current_user
        @followed_user = User.find(params[:followed_user_id])
        #puts '-----------------------------------------------------------------'
        #puts @user.username, 'is following', @followed_user.username
        #puts @user.id.to_s == params[:followed_user_id].to_s
        #puts '-----------------------------------------------------------------'
        @user.follow!(@followed_user)
        # send notifications to user
        @followed_user.create_notification("#{@user.username} is now following you", "#{@user.username} is now following you")
        redirect_back fallback_location: user_path(@followed_user)
    end
    
    def unfollow
        @user = current_user
        @follow = @user.followers.detect{|e| e.follower.id.to_i == params[:followed_user_id].to_i}
        #puts '-----------------------------------------------------------------'
        #puts @user.id, 'is unfollowing', params[:followed_user_id], '| deleting follow', @follow
        #puts @user.followers.any? {|e| e.follower.id.to_i == params[:followed_user_id].to_i}
        #puts @user.followers[0].follower.id.to_s
        #puts '|', @user.followers.length, '|'
        #puts '-----------------------------------------------------------------'
        @followed_user = User.find(params[:followed_user_id])
        @follow.destroy!
        redirect_back fallback_location: user_path(@followed_user)
    end
end

app/views/follows/_button.html.erb
<% if logged_in? %>
    <% if current_user.follow?(followed_user) %>
        <%= button_to unfollow_path(followed_user_id: followed_user.id), remote: true, method: :delete, :class => "btn btn-primary" do %>
            <i class="icon-low material-icons" style="font-size: 20px;">supervisor_account</i> Unfollow
        <% end %>
    <% else %>
        <%= button_to follow_path(followed_user_id: followed_user.id), remote: true, :class => "btn btn-primary" do %>
            <i class="icon-low material-icons" style="font-size: 20px;">supervisor_account</i> Follow
        <% end %>
    <% end %>
<% end %>

app/views/follows/follow.js.erb
$('div#<%= dom_id(@user) %>').html('<%= j render partial: "button", locals: {followed_user: @user} %>');

app/views/follows/unfollow.js.erb
$('div#<%= dom_id(@user) %>').html('<%= j render partial: "button", locals: {followed_user: @user} %>');