config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/discord', to: 'pages#discord'
  get '/signup', to: 'users#new'
  
  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete
  
  match 'follow', to: 'follows#follow', via: :post
  match 'unfollow', to: 'follows#unfollow', via: :delete
  
  match 'notifications/send', to: 'notifications#create', via: :post
  
  resources :notifications, only: [:show] do
    member do
      match :read, to: 'notifications#read', via: :post
      match :delete, to: 'notifications#delete', via: :delete
    end
  end
  
  resources :users do
    member do
      get :notifications
      post :read_all_notifications
      post :delete_all_notifications
    end
  end
  
  resources :users, except: [:new]
  resources :posts
  resources :comments, except: [:new, :index, :show] do
    member do
      put :undelete
    end
  end
  
  post 'comments/new', to: 'comments#create'
  
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% alert name do %>
    <%= msg %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <ul class="navbar-body span-if-nano span-if-xs span-if-sm">
    <li class="navbar-btn"><span style="font-size:30px;cursor:pointer" onclick="openSideBar('mySidenav')"><i class="material-icons navbar-btn-link-icon" style="font-size: 38px;">menu</i></span></li>
    <li class="navbar-btn"><%= link_to "home", root_path, :class => "navbar-btn-link-icon material-icons", :style => "font-size: 38px;" %></li>
    <% if logged_in? then %>
      <li class="navbar-btn-r"><%= link_to user_path(current_user), :class => "navbar-btn-link-icon material-icons", :style => "font-size: 38px;" do %><%= gravatar_for current_user, size: 38, animated: true %><% end %></li>
      <li class="navbar-btn"><%= link_to "Logout", logout_path, method: :delete, :class => "navbar-btn-link" %></li>
    <% else %>
      <li class="navbar-btn"><%= link_to "Login", login_path, :class => "navbar-btn-link" %></li>
    <% end %>
  </ul>
  <ul class="navbar-body span-if-med span-if-lg span-if-xl" id="navbar-body">
    <span class="navbar-btn" style="font-size:30px;cursor:pointer" onclick="openSideBar('mySidenav')"><i class="material-icons navbar-btn-link-icon" style="font-size: 38px;">menu</i></span>
    <li class="navbar-btn"><%= link_to "home", root_path, :class => "navbar-btn-link-icon material-icons", :style => "font-size: 38px;" %></li>
    <li class="navbar-btn"><%= link_to "Users", users_path, :class => "navbar-btn-link" %></li>
    <li class="navbar-btn"><%= link_to "Posts", posts_path, :class => "navbar-btn-link" %></li>
    <li class="navbar-btn"><%= link_to "Discord", discord_path, :class => "navbar-btn-link" %></li>
    <% if logged_in? then %>
      <li class="navbar-btn-r"><%= link_to user_path(current_user), :class => "navbar-btn-link-icon-idle material-icons", :style => "font-size: 38px;" do %><%= gravatar_for current_user, size: 38, animated: true %><% end %></li>
      <li class="navbar-btn-r">
        <%= link_to notifications_user_path(current_user), :class => "navbar-btn-link-icon" do %>
          <i class="icon-low material-icons" style="font-size: 38px;">notifications</i><!-- KEEP ME! comment to remove new line (destroys the layout)
          --><span class="notify-bubble-container">
            <% notifications = Notification.where(:user => current_user, :read => false).length %>
            <% if notifications < 1 then %>
            <% elsif notifications < 10 then %>
              <span class="notify-bubble-small">
                <%= notifications %>
              </span>
            <% elsif notifications < 100 then %>
              <span class="notify-bubble">
                <%= notifications %>
              </span>
            <% else %>
              <span class="notify-bubble">
                <%= "99+" %>
              </span>
            <% end %>
          </span>
        <% end %>
      </li>
      <li class="navbar-btn"><%= link_to "Logout", logout_path, method: :delete, :class => "navbar-btn-link" %></li>
    <% else %>
      <li class="navbar-btn"><%= link_to "Login", login_path, :class => "navbar-btn-link" %></li>
    <% end %>
  </ul>
</nav>

<div id="mySidenav" class="sidebar">
  <a href="javascript:void(0)" class="sidebar-btn sidebar-closebtn" onclick="closeSideBar('mySidenav')">&times;</a>
  <%= link_to root_path, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">home</i> Home<% end %>
  <%= link_to users_path, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">people</i> Users<% end %>
  <%= link_to posts_path, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">description</i> Posts<% end %>
  <%= link_to discord_path, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">chat</i> Discord<% end %>
  <% if logged_in? then %>
    <%= link_to notifications_user_path(current_user), :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">notifications</i> Notifications<% end %>
    <%= link_to user_path(current_user), :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">person</i> Your profile<% end %>
    <%= link_to logout_path, method: :delete, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">power_settings_new</i> Logout<% end %>
  <% else %>
    <%= link_to login_path, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">lock_open</i> Login<% end %>
    <%= link_to signup_path, :class => "sidebar-btn" do %><i class="icon-low material-icons" style="font-size: 38px;">person_add</i> Signup<% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hmi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>
</div>

<script>
  function fade(element) {
      var op = 1;  // initial opacity
      var timer = setInterval(function () {
          if (op <= 0.1){
              clearInterval(timer);
              element.style.display = 'none';
          }
          element.style.opacity = op;
          element.style.filter = 'alpha(opacity=' + op * 100 + ")";
          op -= op * 0.1;
      }, 25);
  }
  
  var close = document.getElementsByClassName("closebtn");
  var i;
  
  for (i = 0; i < close.length; i++) {
      close[i].onclick = function() {
          var div = this.parentElement;
          fade(div);
      }
  }
  
  $(document).on('ready page:load', function () {
    var isLoading = false;
    if ($('#infinite-scrolling').size() > 0) {
      $(window).on('scroll', function() {
        var more_posts_url = $('.pagination a.next_page').attr('href');
        if (!isLoading && more_posts_url && $(window).scrollTop() > $(document).height() - $(window).height() - 60) {
          isLoading = true;
          $.getScript(more_posts_url).done(function (data,textStatus,jqxhr) {
            isLoading = false;
          }).fail(function() {
            isLoading = false;
          });
        }
      });
    }
  });
  </script>

</body>
</html>